version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/TAEHOONNOTE

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Gatsby Build
          command: yarn build

      - run:
          name: Firebase Deploy
          command: yarn deploy