version: 2.1

executors:
  default:
    working_directory: ~/taehoonnote

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
  build:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run build
      - store_artifacts:
          path: ~/taehoonnote/public
          destination: public
      - persist_to_workspace:
          root: ~/
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run serve

workflows:
  test-and-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
