version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
            - public
            - package.json
            - firebase.json

      - run: yarn test

    deploy:
    docker:
        - image: circleci/node:chakracore-8.11-browsers-legacy
    working_directory: ~/repo
    steps:
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        - restore_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Install Firebase
            command: npm install --save-dev firebase-tools
        - run:
            name: Deploy Master to Firebase
            command: yarn run deploy