version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.15.3
  working_directory: ~/taehoonnote

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test --runInBand --no-cache

  build-and-deploy:
    <<: *defaults
    branch: master
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run build
      - run: yarn run deployFirebase --token=$FIREBASE_TOKEN --non-interactive --project=$FIREBASE_PROJECT

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install
      - build-and-deploy:
          requires:
            - install
          context: Firebase
          filters:
            branches:
              only: master
