version: 2.1

executors:
  default:
    working_directory: ~/TAEHOONNOTE
    docker:
      - image: circleci/node:8

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  build:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Gatsby Build
          command: yarn build
      - store_artifacts:
          path: ~/circleci/TAEHOONNOTE/public
          destination: public
      - persist_to_workspace:
          root: ~/
          paths:
            - circleci

  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Firebase Deploy
          command: yarn deploy

workflows:
  deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
